/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC </br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/


USE listproject;

CREATE TABLE Master_List(
id bigint(19) NOT NULL auto_increment,
created_date datetime NOT NULL ,
created_by bigint(19) NOT NULL DEFAULT 0,
updated_date datetime NOT NULL ,
updated_by bigint(19) NOT NULL DEFAULT 0,
title varchar(255),
description varchar(255),
listid bigint(19),
PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE ListType(
id bigint(19) NOT NULL auto_increment,
created_date datetime NOT NULL ,
created_by bigint(19) NOT NULL DEFAULT 0,
updated_date datetime NOT NULL ,
updated_by bigint(19) NOT NULL DEFAULT 0,
name varchar(255),
Master_List_id bigint(19) NOT NULL UNIQUE,
PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE Task(
id bigint(19) NOT NULL auto_increment,
created_date datetime NOT NULL ,
created_by bigint(19) NOT NULL DEFAULT 0,
updated_date datetime NOT NULL ,
updated_by bigint(19) NOT NULL DEFAULT 0,
taskid bigint(19),
title varchar(255),
description varchar(255),
taskowner varchar(255),
duedate Date,
completionpercentage bigint(19),
attachment MEDIUMBLOB,
groupid bigint(19),
PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE TaskGroup(
id bigint(19) NOT NULL auto_increment,
created_date datetime NOT NULL ,
created_by bigint(19) NOT NULL DEFAULT 0,
updated_date datetime NOT NULL ,
updated_by bigint(19) NOT NULL DEFAULT 0,
groupid bigint(19),
groupname varchar(255),
description varchar(255),
PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE TaskPriority(
id bigint(19) NOT NULL auto_increment,
created_date datetime NOT NULL ,
created_by bigint(19) NOT NULL DEFAULT 0,
updated_date datetime NOT NULL ,
updated_by bigint(19) NOT NULL DEFAULT 0,
name varchar(255),
Task_id bigint(19) NOT NULL UNIQUE,
PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE TaskStatus(
id bigint(19) NOT NULL auto_increment,
created_date datetime NOT NULL ,
created_by bigint(19) NOT NULL DEFAULT 0,
updated_date datetime NOT NULL ,
updated_by bigint(19) NOT NULL DEFAULT 0,
name varchar(255),
Task_id bigint(19) NOT NULL UNIQUE,
PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

