package com.ListProject.service;

import java.util.ArrayList;

import javax.annotation.Resource;

import org.springframework.stereotype.Service;

import com.ListProject.dao.mysql.GpUserDAO;
import com.ListProject.domain.core.GpUser;



/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
@Service("Gp_Default_ActivityService")
public class Gp_Default_ActivityService extends GpBaseService  {
	
	GpUserDAO Gp_Default_ActivityDao;

	
	
	public GpUserDAO get_Gp_Default_ActivityDao() {
		return Gp_Default_ActivityDao;
	}

	@Resource(name="GpUserDAO")
	public void set_Gp_Default_ActivityDao(GpUserDAO Gp_Default_ActivityDao) {
		this.Gp_Default_ActivityDao = Gp_Default_ActivityDao;
	}


	//auths not ready at this time
	public ArrayList<GpUser> getallUsers() throws Exception {


		try{
			ArrayList<GpUser> assign_to;

			assign_to = Gp_Default_ActivityDao.getallUsers();
			
			return assign_to;

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());

		}
		return null;

	}


}