package com.ListProject.service;

import java.util.ArrayList;

import javax.annotation.Resource;
import org.springframework.stereotype.Service;

import com.ListProject.domain.core.Master_List;

import com.ListProject.dao.mysql.Master_List_Default_ActivityDao;

import com.ListProject.domain.core.GpUser;

/**
 *
 * @author Geppetto Generated Code</br>
 *         Date Created: </br>
 * @since </br>
 *        build:
 *        </p>
 *
 *        code was generated by the Geppetto System </br>
 *        Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 *        The generated code is free to use by anyone
 *        </p>
 *
 *
 *
 */
@Service("Master_List_Default_ActivityService")
public class Master_List_Default_ActivityService extends GpBaseService {

	Master_List_Default_ActivityDao Master_List_Default_Activity_dao;

	public Master_List_Default_ActivityDao get_Master_List_Default_Activity_dao() {
		return Master_List_Default_Activity_dao;
	}

	@Resource(name = "Master_List_Default_ActivityDao")
	public void set_Master_List_Default_Activity_dao(Master_List_Default_ActivityDao Master_List_Default_Activity_dao) {
		this.Master_List_Default_Activity_dao = Master_List_Default_Activity_dao;
	}

	// auths not ready at this time
	public Master_List create_master_list(Master_List Master_List, GpUser user) throws Exception {

		try {
			Master_List the_Master_List;

			the_Master_List = Master_List_Default_Activity_dao.create_master_list(Master_List, user);

			return the_Master_List;

		} catch (Exception e) {

			System.out.println("ServiceException: " + e.toString());

		}
		return null;

	}

	// auths not ready at this time
	public Master_List update_master_list(Master_List Master_List, GpUser user) throws Exception {

		try {
			Master_List the_Master_List;

			the_Master_List = Master_List_Default_Activity_dao.update_master_list(Master_List, user);

			return the_Master_List;

		} catch (Exception e) {

			System.out.println("ServiceException: " + e.toString());

		}
		return null;

	}

	// auths not ready at this time
	public Master_List master_list_search_for_update(long id, GpUser user) throws Exception {

		try {
			Master_List the_Master_List;

			the_Master_List = Master_List_Default_Activity_dao.master_list_search_for_update(id, user);

			return the_Master_List;

		} catch (Exception e) {

			System.out.println("ServiceException: " + e.toString());

		}
		return null;

	}

	// auths not ready at this time
	public String delete_master_list(long id, GpUser user) throws Exception {

		try {
			String method_return_message;

			method_return_message = Master_List_Default_Activity_dao.delete_master_list(id, user);

			return method_return_message;

		} catch (Exception e) {

			System.out.println("ServiceException: " + e.toString());

		}
		return null;

	}

	// auths not ready at this time
	public ArrayList<Master_List> get_all_master_list() throws Exception {

		try {
			ArrayList<Master_List> Master_List_list;

			Master_List_list = Master_List_Default_Activity_dao.get_all_master_list();
			/*
			 * for(Master_List Master_List : Master_List_list){
			 * Master_List.setListtype(ListType_Default_ActivityService.
			 * get_listtype_by_parent_id(Master_List.getId())); }
			 */
			return Master_List_list;

		} catch (Exception e) {

			System.out.println("ServiceException: " + e.toString());

		}
		return null;

	}

}