package com.ListProject.dao.mysql;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import java.util.HashMap;
import java.util.Map;

import javax.annotation.Resource;
import javax.persistence.Column;
import javax.persistence.Query;
import javax.persistence.Transient;
import javax.sound.midi.SysexMessage;
import javax.sql.DataSource;
import javax.transaction.Transactional;


import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.FlushModeType;
import javax.persistence.PersistenceContext;
import javax.persistence.PersistenceUnitUtil;
import javax.transaction.Transactional;
import javax.persistence.Query;


import javax.annotation.Resource;
import javax.sql.DataSource;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Repository;



import com.ListProject.domain.core.TaskPriority;
import com.ListProject.domain.core.GpUser;


/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
@Transactional
@Repository("TaskPriority_Default_ActivityDao")
public class TaskPriority_Default_ActivityDao   {

	private Log log = LogFactory.getLog(getClass());

	@Value("${create_TaskPriority.sql}")
	private String create_TaskPriority;
	@Value("${search_for_update_TaskPriority.sql}")
	private String search_for_update_TaskPriority;
	@Value("${update_TaskPriority.sql}")
	private String update_TaskPriority;
	@Value("${delete_TaskPriority.sql}")
	private String delete_TaskPriority;
	@Value("${get_all_TaskPriority.sql}")
	private String get_all_TaskPriority;
	@Value("${get_by_parent_id_TaskPriority.sql}")
	private String get_by_parent_id_TaskPriority;
	@Value("${delete_by_parent_id_TaskPriority.sql}")
	private String delete_by_parent_id_TaskPriority;


    @PersistenceContext
	EntityManager entityManager;



	//auths not ready at this time
	public TaskPriority taskpriority_search_for_update(long id, GpUser user) throws Exception {


		try{

			Query result =  entityManager.
			createNativeQuery(search_for_update_TaskPriority,TaskPriority.class)

			.setParameter("id", id);;

			ArrayList<TaskPriority> TaskPriority_list =	(ArrayList<TaskPriority>)result.getResultList();

			if(TaskPriority_list  == null){
				throw new Exception("no TaskPriority found");
			}

			return (TaskPriority) TaskPriority_list.get(0);

		}catch(Exception e){

			new Exception(e.toString());  // this needs to be changed

		}
		return null;


	}

	//auths not ready at this time
	public ArrayList<TaskPriority> get_all_taskpriority() throws Exception {


		try{

			Query result =  entityManager.
			createNativeQuery(get_all_TaskPriority,TaskPriority.class)

;

			ArrayList<TaskPriority> TaskPriority_list =	(ArrayList<TaskPriority>)result.getResultList();

			if(TaskPriority_list .size() < 1){
				throw new Exception("no TaskPriority found");
			}

			return (ArrayList<TaskPriority>) TaskPriority_list;

		}catch(Exception e){

			new Exception(e.toString());  // this needs to be changed

		}
		return null;


	}

	//auths not ready at this time
	public TaskPriority get_taskpriority_by_parent_id(long Task_id) throws Exception {


		try{

			Query result =  entityManager.
			createNativeQuery(get_by_parent_id_TaskPriority,TaskPriority.class)

			.setParameter("Task_id", Task_id == 0 ? "%%" : Task_id);

			ArrayList<TaskPriority> TaskPriority_list =	(ArrayList<TaskPriority>)result.getResultList();

			if(TaskPriority_list  == null){
				throw new Exception("no TaskPriority found");
			}

			return (TaskPriority) TaskPriority_list.get(0);

		}catch(Exception e){

			new Exception(e.toString());  // this needs to be changed

		}
		return null;


	}



	//auths not ready at this time
	@Transactional
	public TaskPriority create_taskpriority(TaskPriority TaskPriority, GpUser user) throws Exception {


		try{
			Query query = entityManager
					.createNativeQuery(create_TaskPriority)
			.setParameter("name", TaskPriority.getName())
			.setParameter("Task_id", TaskPriority.getTask_id())
			.setParameter("created_by", user == null ? 0:user.getId())
			.setParameter("updated_by", user == null ? 0:user.getId())
;

			int insertedId = query.executeUpdate();
					String lastIndex="select last_insert_id()";
					Query sql = entityManager.createNativeQuery(lastIndex);
					BigInteger new_id = (BigInteger) sql.getSingleResult();
					TaskPriority.setId(new_id.longValue());
					System.out.println("create data---"+insertedId);

			return TaskPriority;

		}catch(Exception e){

			System.out.println("DAOException: " + e.toString());

		}
		return null;



	}

	//auths not ready at this time
	@Transactional
	public TaskPriority update_taskpriority(TaskPriority TaskPriority, GpUser user) throws Exception {


		try{
			Query query = entityManager
					.createNativeQuery(update_TaskPriority)
			.setParameter("id", TaskPriority.getId())
			.setParameter("name", TaskPriority.getName())
			.setParameter("Task_id", TaskPriority.getTask_id())
			.setParameter("updated_by", user == null ? 0:user.getId())
;

			query.executeUpdate();

			return TaskPriority;

		}catch(Exception e){

			System.out.println("DAOException: " + e.toString());

		}
		return null;



	}

	//auths not ready at this time
	@Transactional
	public String  delete_taskpriority(long id, GpUser user) throws Exception {


		try{
			Query query = entityManager
					.createNativeQuery(delete_TaskPriority)
			.setParameter("id", id);

			query.executeUpdate();

			return "{\"status\":\"success\"}";

		}catch(Exception e){

			System.out.println("DAOException: " + e.toString());

		}
		return null;



	}

	//auths not ready at this time
	@Transactional
	public String  delete_taskpriority_by_parent_id(long Task_id) throws Exception {


		try{
			Query query = entityManager
					.createNativeQuery(delete_by_parent_id_TaskPriority)
			.setParameter("Task_id", Task_id == 0 ? "%%" : Task_id);

			query.executeUpdate();

			return "{\"status\":\"success\"}";

		}catch(Exception e){

			System.out.println("DAOException: " + e.toString());

		}
		return null;



	}



}