package com.ListProject.controller;

import java.util.ArrayList;

import javax.annotation.Resource;

import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RequestBody;

import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;
import com.wordnik.swagger.annotations.ApiResponse;
import com.wordnik.swagger.annotations.ApiResponses;


import com.ListProject.domain.core.TaskPriority;

import com.ListProject.service.TaskPriority_Default_ActivityService;



/**
 * 
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p> 
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

@Api(value = "/TaskPriority_Default_Activity", description = "TaskPriority_Default_Activity of TaskPriority_Default_Activity", 
produces = "application/json")

@Controller("TaskPriority_Default_ActivityController")
@RequestMapping("/TaskPriority_Default_Activity")
public class TaskPriority_Default_ActivityController extends GpBaseController {


	TaskPriority_Default_ActivityService TaskPriority_Default_Activity_service;


	public TaskPriority_Default_ActivityService get_TaskPriority_Default_Activity_service() {
		return TaskPriority_Default_Activity_service;
	}


	@Resource(name="TaskPriority_Default_ActivityService")
	public void set_TaskPriority_Default_Activity_service(TaskPriority_Default_ActivityService TaskPriority_Default_Activity_service) {
		this.TaskPriority_Default_Activity_service = TaskPriority_Default_Activity_service;
	}




	//auths not ready at this time


	@ApiOperation(value = "/create_TaskPriority", httpMethod = "POST",
	notes = "creates a noun of TaskPriority", 
	response = TaskPriority.class)
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "The request was fulfilled"),
	    @ApiResponse(code = 404, message = "The server has not found anything matching the URI given"),
	    @ApiResponse(code = 500, message = "Internal server error due to encoding the data"),
	    @ApiResponse(code = 400, message = "Bad request due to decoding the data"),
	    @ApiResponse(code = 412, message = "Pre condition failed due to required data not found") })

	@RequestMapping(method = RequestMethod.POST,value = "/create_TaskPriority" ,headers="Accept=application/json")
    @ResponseBody
	public TaskPriority create_TaskPriority(@RequestBody TaskPriority the_TaskPriority) throws Exception {

		TaskPriority a_TaskPriority;

		a_TaskPriority = TaskPriority_Default_Activity_service.create_taskpriority(the_TaskPriority, super.getUser());

		return a_TaskPriority;

	}

	//auths not ready at this time


	@ApiOperation(value = "/update_TaskPriority", httpMethod = "PUT",
	notes = "updates a noun of TaskPriority", 
	response = TaskPriority.class)
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "The request was fulfilled"),
	    @ApiResponse(code = 404, message = "The server has not found anything matching the URI given"),
	    @ApiResponse(code = 500, message = "Internal server error due to encoding the data"),
	    @ApiResponse(code = 400, message = "Bad request due to decoding the data"),
	    @ApiResponse(code = 412, message = "Pre condition failed due to required data not found") })

	@RequestMapping(method = RequestMethod.PUT,value = "/update_TaskPriority" ,headers="Accept=application/json")
    @ResponseBody
	public TaskPriority update_TaskPriority(@RequestBody TaskPriority the_TaskPriority) throws Exception {

		TaskPriority a_TaskPriority;

		a_TaskPriority = TaskPriority_Default_Activity_service.update_taskpriority(the_TaskPriority, super.getUser());

		return a_TaskPriority;

	}

	//auths not ready at this time


	@ApiOperation(value = "/search_for_update_TaskPriority/{TaskPriority_id}", httpMethod = "GET",
	notes = "updates a noun of TaskPriority", 
	response = TaskPriority.class)
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "The request was fulfilled"),
	    @ApiResponse(code = 404, message = "The server has not found anything matching the URI given"),
	    @ApiResponse(code = 500, message = "Internal server error due to encoding the data"),
	    @ApiResponse(code = 400, message = "Bad request due to decoding the data"),
	    @ApiResponse(code = 412, message = "Pre condition failed due to required data not found") })

	@RequestMapping(method = RequestMethod.GET,value = "/search_for_update_TaskPriority/{TaskPriority_id}" ,headers="Accept=application/json")
    @ResponseBody
	public TaskPriority search_for_update_TaskPriority(@PathVariable("TaskPriority_id")long TaskPriority_id) throws Exception {

		TaskPriority the_TaskPriority = new TaskPriority();

		the_TaskPriority = TaskPriority_Default_Activity_service.taskpriority_search_for_update(TaskPriority_id, super.getUser());

		return the_TaskPriority;

	}

	//auths not ready at this time


	@ApiOperation(value = "/delete_TaskPriority/{TaskPriority_id}", httpMethod = "DELETE",
	notes = "deletes a noun of TaskPriority", 
	response = TaskPriority.class)
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "The request was fulfilled"),
	    @ApiResponse(code = 404, message = "The server has not found anything matching the URI given"),
	    @ApiResponse(code = 500, message = "Internal server error due to encoding the data"),
	    @ApiResponse(code = 400, message = "Bad request due to decoding the data"),
	    @ApiResponse(code = 412, message = "Pre condition failed due to required data not found") })

	@RequestMapping(method = RequestMethod.DELETE,value = "/delete_TaskPriority/{TaskPriority_id}" ,headers="Accept=application/json")
    @ResponseBody
	public String  delete_TaskPriority(@PathVariable("TaskPriority_id")long TaskPriority_id) throws Exception {

		String service_return_msg = "";

		service_return_msg = TaskPriority_Default_Activity_service.delete_taskpriority(TaskPriority_id, super.getUser());

		return service_return_msg;

	}

	//auths not ready at this time


	@ApiOperation(value = "/get_all_TaskPriority", httpMethod = "GET",
	notes = "special search that gets all values of TaskPriority", 
	response = TaskPriority.class)
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "The request was fulfilled"),
	    @ApiResponse(code = 404, message = "The server has not found anything matching the URI given"),
	    @ApiResponse(code = 500, message = "Internal server error due to encoding the data"),
	    @ApiResponse(code = 400, message = "Bad request due to decoding the data"),
	    @ApiResponse(code = 412, message = "Pre condition failed due to required data not found") })

	@RequestMapping(method = RequestMethod.GET,value = "/get_all_TaskPriority" ,headers="Accept=application/json")
    @ResponseBody
	public ArrayList<TaskPriority> get_all_TaskPriority() throws Exception {

		ArrayList<TaskPriority> TaskPriority_list = new ArrayList<TaskPriority>();

		TaskPriority_list = TaskPriority_Default_Activity_service.get_all_taskpriority();

		return TaskPriority_list;

	}

	//auths not ready at this time


	@ApiOperation(value = "/get_TaskPriority_by_parent_id", httpMethod = "GET",
	notes = "get by parent id of TaskPriority", 
	response = TaskPriority.class)
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "The request was fulfilled"),
	    @ApiResponse(code = 404, message = "The server has not found anything matching the URI given"),
	    @ApiResponse(code = 500, message = "Internal server error due to encoding the data"),
	    @ApiResponse(code = 400, message = "Bad request due to decoding the data"),
	    @ApiResponse(code = 412, message = "Pre condition failed due to required data not found") })

	@RequestMapping(method = RequestMethod.GET,value = "/get_TaskPriority_by_parent_id" )
    @ResponseBody
	public TaskPriority get_TaskPriority_by_parent_id(@RequestParam(required = false, value = "Task_id", defaultValue = "0") long Task_id) throws Exception {

		TaskPriority a_TaskPriority;

		a_TaskPriority = TaskPriority_Default_Activity_service.get_taskpriority_by_parent_id(Task_id);

		return a_TaskPriority;

	}

	//auths not ready at this time


	@ApiOperation(value = "/delete_TaskPriority_by_parent_id", httpMethod = "DELETE",
	notes = "delete by parent of TaskPriority", 
	response = TaskPriority.class)
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "The request was fulfilled"),
	    @ApiResponse(code = 404, message = "The server has not found anything matching the URI given"),
	    @ApiResponse(code = 500, message = "Internal server error due to encoding the data"),
	    @ApiResponse(code = 400, message = "Bad request due to decoding the data"),
	    @ApiResponse(code = 412, message = "Pre condition failed due to required data not found") })

	@RequestMapping(method = RequestMethod.DELETE,value = "/delete_TaskPriority_by_parent_id" )
    @ResponseBody
	public String  delete_TaskPriority_by_parent_id(@RequestParam(required = false, value = "Task_id", defaultValue = "0") long Task_id) throws Exception {

		String service_return_msg = "";

		service_return_msg = TaskPriority_Default_Activity_service.delete_taskpriority_by_parent_id(Task_id);

		return service_return_msg;

	}




}