package com.ListProject.domain.core;


/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.wordnik.swagger.annotations.ApiModel;
import com.wordnik.swagger.annotations.ApiModelProperty;


@Entity

@Table(name="ListType")

@JsonIgnoreProperties(ignoreUnknown = true)

@ApiModel( value = "ListType", description = "ListType" )
@JsonInclude(Include.NON_NULL)
public class ListType  {


	@ApiModelProperty( value = "The standard id attribute - System generated", required = true )
	@Id 
 	@GeneratedValue
 	long Id;



	@ApiModelProperty( value = "created date", required = true )
	@Column
 	String Created_date;



	@ApiModelProperty( value = "created by value", required = true )
	@Column
 	long Created_by;



	@ApiModelProperty( value = "updated date", required = true )
	@Column
 	String Updated_date;



	@ApiModelProperty( value = "updated by value", required = true )
	@Column
 	long Updated_by;



	@ApiModelProperty( value = "description", required = true )
	@Column
 	String Name;



	@ApiModelProperty( value = "parent id", required = true )
	@Column
 	long Master_List_id;




	public void setId(long Id) {
		this.Id = Id;
	}


	public long getId() {
		return Id;
	}

	public void setCreated_date(String Created_date) {
		this.Created_date = Created_date;
	}


	public String getCreated_date() {
		return Created_date;
	}

	public void setCreated_by(long Created_by) {
		this.Created_by = Created_by;
	}


	public long getCreated_by() {
		return Created_by;
	}

	public void setUpdated_date(String Updated_date) {
		this.Updated_date = Updated_date;
	}


	public String getUpdated_date() {
		return Updated_date;
	}

	public void setUpdated_by(long Updated_by) {
		this.Updated_by = Updated_by;
	}


	public long getUpdated_by() {
		return Updated_by;
	}

	public void setName(String Name) {
		this.Name = Name;
	}


	public String getName() {
		return Name;
	}

	public void setMaster_List_id(long Master_List_id) {
		this.Master_List_id = Master_List_id;
	}


	public long getMaster_List_id() {
		return Master_List_id;
	}




}