package com.ListProject.domain.core;

import java.util.Date;

/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.wordnik.swagger.annotations.ApiModel;
import com.wordnik.swagger.annotations.ApiModelProperty;

@Entity

@Table(name = "task")

@JsonIgnoreProperties(ignoreUnknown = true)

@ApiModel(value = "task", description = "task")
@JsonInclude(Include.NON_NULL)
public class Task {

	@ApiModelProperty(value = "The standard id attribute - System generated", required = true)
	@Id
	@GeneratedValue
	long Id;

	@ApiModelProperty(value = "created date", required = true)
	@Column
	String Created_date;
	
	@ApiModelProperty(value = "user_name", required = true)
	@Transient
	GpUser username;
	
	@ApiModelProperty(value = "task_owner_user", required = true)
	@Transient
	GpUser taskOwnerUser;

	@ApiModelProperty(value = "created by value", required = true)
	@Column
	long Created_by;

	@ApiModelProperty(value = "updated date", required = true)
	@Column
	String Updated_date;

	@ApiModelProperty(value = "updated by value", required = true)
	@Column
	long Updated_by;

	@ApiModelProperty(value = "description", required = true)
	@Column
	String Title;

	@ApiModelProperty(value = "description", required = true)
	@Column
	String Description;

	@ApiModelProperty(value = "description", required = true)
	@Column
	long Taskowner;

	@ApiModelProperty(value = "task_status", required = true)
	@Column
	String task_status;

	@ApiModelProperty(value = "task_priority", required = true)
	@Column
	String task_priority;

	public long getTaskowner() {
		return Taskowner;
	}

	public void setTaskowner(long taskowner) {
		Taskowner = taskowner;
	}
	
	@ApiModelProperty(value = "listId", required = true)
	@Column
	Long listId;
	
	@ApiModelProperty(value = "description", required = true)
	@Column
	Date Duedate;

	@ApiModelProperty(value = "description", required = true)
	@Column
	long Completionpercentage;

	@ApiModelProperty(value = "description", required = true)
	@Column
	@Lob
	String Attachment;

	@ApiModelProperty(value = "description", required = true)
	@Column
	long Groupid;

	public void setId(long Id) {
		this.Id = Id;
	}

	public long getId() {
		return Id;
	}

	public void setCreated_date(String Created_date) {
		this.Created_date = Created_date;
	}

	public String getCreated_date() {
		return Created_date;
	}

	public void setCreated_by(long Created_by) {
		this.Created_by = Created_by;
	}

	public long getCreated_by() {
		return Created_by;
	}

	public void setUpdated_date(String Updated_date) {
		this.Updated_date = Updated_date;
	}

	public String getUpdated_date() {
		return Updated_date;
	}

	public void setUpdated_by(long Updated_by) {
		this.Updated_by = Updated_by;
	}

	public long getUpdated_by() {
		return Updated_by;
	}

	public void setTitle(String Title) {
		this.Title = Title;
	}

	public String getTitle() {
		return Title;
	}

	public void setDescription(String Description) {
		this.Description = Description;
	}

	public String getDescription() {
		return Description;
	}

	public Date getDuedate() {
		return Duedate;
	}

	public void setDuedate(Date duedate) {
		Duedate = duedate;
	}

	public void setCompletionpercentage(long Completionpercentage) {
		this.Completionpercentage = Completionpercentage;
	}

	public long getCompletionpercentage() {
		return Completionpercentage;
	}

	public String getAttachment() {
		return Attachment;
	}

	public void setAttachment(String attachment) {
		Attachment = attachment;
	}

	public void setGroupid(long Groupid) {
		this.Groupid = Groupid;
	}

	public long getGroupid() {
		return Groupid;
	}

	public String getTask_status() {
		return task_status;
	}

	public void setTask_status(String task_status) {
		this.task_status = task_status;
	}

	public String getTask_priority() {
		return task_priority;
	}

	public void setTask_priority(String task_priority) {
		this.task_priority = task_priority;
	}

	public Long getListId() {
		return listId;
	}

	public void setListId(Long listId) {
		this.listId = listId;
	}

	public GpUser getUsername() {
		return username;
	}

	public void setUsername(GpUser username) {
		this.username = username;
	}

	public GpUser getTaskOwnerUser() {
		return taskOwnerUser;
	}

	public void setTaskOwnerUser(GpUser taskOwnerUser) {
		this.taskOwnerUser = taskOwnerUser;
	}
}